[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501

[[server.environment]]
key = "VERTEX_LLM_MODEL"
value = "gemini-2.5-flash"

[theme]
primaryColor = "#5B84B1"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
